# Jekyll configuration

name: My testing blog on Github.com
description: A jekyll theme

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
# baseurl: /jekyll-clean
baseurl: ''

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']

theme: jekyll-theme-architect
